import fs from 'node:fs';
import assert from 'node:assert/strict';
import { reviewGacInputs, workbookInputs } from '../shared/gacReview.js';
import { calculateWorkbook } from '../shared/gacWorkbookEngine.js';
const model = JSON.parse(fs.readFileSync('src/data/gacWorkbook.json'));
const corpus = JSON.parse(fs.readFileSync('public/knowledge/gac_knowledge.json'));
const form = { species: 'PFOA', flow: '100', averageFlow: '100', flowUnit: 'm3/h', totalEbctMinutes: '20', series: '2', parallel: '1', densityLbFt3: '30', diameterFt: '10.5', heightFt: '11', bedDepthFt: '6.8', geometryMode: 'manual', redundantVessels: '', carbonLifeMode: 'none' };
assert.equal(reviewGacInputs(form, model, corpus).canCalculate, true);
assert.match(reviewGacInputs({ ...form, averageFlow: '150' }, model).issues[0].message, /exceeds design flow/);
assert.ok(reviewGacInputs({ ...form, series: '1.5' }, model).issues.some(i => /whole number/.test(i.message)));
assert.ok(reviewGacInputs({ ...form, heightFt: '5' }, model).issues.some(i => /10.70 ft/.test(i.message)));
assert.ok(reviewGacInputs({ ...form, bedDepthFt: '0' }, model).issues.length);
const unknown = { ...form, diameterFt: '?', heightFt: '', bedDepthFt: '?' };
const original = JSON.stringify(unknown);
const review = reviewGacInputs(unknown, model, corpus);
assert.equal(review.canCalculate, false);
const candidate = review.suggestions.find(s => s.kind === 'calculated');
assert.ok(candidate, 'Missing dimensions must have a formula-grounded candidate');
assert.ok(candidate.source.includes('AutoSize!'));
const calculated = calculateWorkbook(workbookInputs({ ...unknown, ...candidate.patch }), model);
assert.ok(calculated.actualTotalEbctMinutes >= 20);
assert.equal(JSON.stringify(unknown), original, 'Suggestions must not mutate inputs');
const study = reviewGacInputs({ ...form, totalEbctMinutes: '?' }, model, corpus);
assert.ok(study.questions.some(q => q.field === 'waterType'));
assert.ok(study.suggestions.every(s => s.kind === 'study_scenario' && /not a validated/.test(s.reason)));
assert.ok(study.suggestions.every(s => corpus.records.some(r => r.id === s.id && r.species === form.species)));
const density = reviewGacInputs({ ...form, densityLbFt3: '?' }, model).suggestions[0];
assert.equal(density.kind, 'assumption');
assert.equal(density.patch.densityLbFt3, String(model.assumptions.GAC_density.value));
assert.equal(reviewGacInputs({ ...form, carbonLifeMode: 'bv', carbonLifeValue: '10000', bvDefinition: 'total_series', carbonLifeSource: '?' }, model).canCalculate, false);
console.log('Input review passed: conflicts, expansion, unknowns, valid calculated candidates, provenance, study limitations and read-only suggestions.');
