import assert from 'node:assert/strict';
import fs from 'node:fs';
import { consultKnowledge } from '../shared/gacKnowledgeEngine.js';
const corpus = JSON.parse(fs.readFileSync('public/knowledge/gac_knowledge.json', 'utf8'));
const form = { species: 'PFOA', influentNgL: '100', targetNgL: '4', flow: '100', totalEbctMinutes: '20', series: '2', parallel: '1', ebctSource: 'Example' };
const result = consultKnowledge(corpus, { form });
assert.equal(result.suggestion.patch.totalEbctMinutes, '20');
assert.equal(result.questions[0].field, 'waterType');
assert.ok(result.evidence.every(r => r.species === 'PFOA'));
assert.match(result.suggestion.patch.ebctSource, /sha256:/);
const missing = consultKnowledge(corpus, { form: { ...form, carbonLifeMode: 'freundlich', targetNgL: '' } });
assert.equal(missing.questions[0].field, 'targetNgL');
const stale = consultKnowledge(corpus, { form, graph: { nodes: [{ type: 'Equipment', id: 'v1', attributes: { calculationState: 'stale' } }] } });
assert.equal(stale.questions[0].field, 'recalculate');
const other = consultKnowledge(corpus, { query: 'Find PFOS conditions', form });
assert.ok(other.evidence.every(r => r.species === 'PFOS')); assert.equal(other.suggestion, null);
const selected = consultKnowledge(corpus, { form: { ...form, referenceId: result.suggestion.referenceId } });
assert.ok(selected.knowledgeGraph.links.some(l => l.label === 'selected_basis'));
assert.ok(corpus.records.some(r => r.bv10pct.status !== 'observed'));
console.log('Workbook retrieval, citations, contextual questions and species isolation passed.');
