import fs from 'node:fs';
import assert from 'node:assert/strict';
import { answerWorkbookQuestion, buildWorkbookGraph, nextWorkbookStep } from '../shared/gacContext.js';
const model = JSON.parse(fs.readFileSync('src/data/gacWorkbook.json', 'utf8'));
const form = { species: 'PFOA', flow: '100', flowUnit: 'm3/h', averageFlow: '100', totalEbctMinutes: '20', series: '2', diameterFt: '10.5', heightFt: '11', bedDepthFt: '6.8', densityLbFt3: '30', carbonLifeMode: 'none' };
const context = { form, graph: { nodes: [], links: [] }, proposal: null, accepted: null };
const original = JSON.stringify(context);
assert.equal(nextWorkbookStep(context).action, 'calculate');
const question = answerWorkbookQuestion('What is EBCT? Show the Excel source.', context, model);
assert.match(question.message, /INPUT!G46/); assert.ok(question.fields.includes('totalEbctMinutes'));
const brief = answerWorkbookQuestion('What is EBCT?', context, model);
assert.ok(!brief.message.includes('INPUT!')); assert.ok(!brief.message.includes('Current input'));
const connection = answerWorkbookQuestion('Which formulas depend on design flow?', context, model);
assert.match(connection.message, /Contactor Constraints!C38/);
assert.equal(answerWorkbookQuestion('What should I do next?', context, model).action, 'calculate');
const missing = { ...context, form: { ...form, carbonLifeMode: 'bv', carbonLifeValue: '' } };
assert.ok(nextWorkbookStep(missing).fields.includes('carbonLifeValue'));
assert.equal(nextWorkbookStep({ ...context, graph: { nodes: [{ attributes: { calculationState: 'stale' } }] } }).action, 'recalculate');
assert.equal(nextWorkbookStep({ ...context, proposal: {} }).action, 'review');
assert.equal(nextWorkbookStep({ ...context, accepted: {} }).action, 'refine');
const kg = buildWorkbookGraph(form, null, model, context.graph);
const ids = new Set(kg.nodes.map(n => n.id));
assert.ok(kg.links.every(l => ids.has(l.source) && ids.has(l.target)));
assert.ok(kg.nodes.filter(n => n.type === 'ExcelCalculation').every(n => typeof n.attributes.formula === 'string'));
const months = buildWorkbookGraph({ ...form, carbonLifeMode: 'months', carbonLifeValue: '12' }, null, model, context.graph);
assert.deepEqual(months.links.filter(l => l.target === 'life').map(l => l.source), ['carbonLifeValue']);
assert.equal(JSON.stringify(context), original, 'Questions must not change any input or graph');
console.log('Workbook Q&A, next steps, formula graph dependencies and read-only explanations passed.');
